import type { AppLanguage } from '@folio/shared-types'

// Simplified-Chinese display labels for Exif tag field names (group-stripped), keyed by the raw
// ExifTool family-0 tag name. Coverage is scoped to the tags a typical iPhone HEIC produces
// (reference: .dev/IMG_6046.HEIC) plus the common content/rights tags surfaced in the summary.
// English keeps the conventional ExifTool tag name (what en users expect), so only zh-CN needs a
// map; unknown tags fall back to the raw key in any language.
const ZH: Record<string, string> = {
  // File
  Directory: '目录',
  ExifByteOrder: '字节序',
  FileAccessDate: '访问日期',
  FileInodeChangeDate: '节点变更日期',
  FileModifyDate: '修改日期',
  FileName: '文件名',
  FilePermissions: '文件权限',
  FileSize: '文件大小',
  FileType: '文件类型',
  FileTypeExtension: '文件扩展名',
  ImageHeight: '图像高度',
  ImageWidth: '图像宽度',
  MIMEType: 'MIME 类型',
  BitsPerSample: '采样位数',
  ColorComponents: '颜色分量',
  EncodingProcess: '编码方式',
  YCbCrSubSampling: 'YCbCr 子采样',

  // JPEG / APP14 (Adobe)
  APP14Flags0: 'APP14 标志 0',
  APP14Flags1: 'APP14 标志 1',
  ColorTransform: '色彩变换',
  DCTEncodeVersion: 'DCT 编码版本',

  // EXIF
  ApertureValue: '光圈值',
  BrightnessValue: '亮度值',
  ColorSpace: '色彩空间',
  CompositeImage: '合成图像',
  CreateDate: '创建时间',
  DateTimeOriginal: '原始拍摄时间',
  DigitalZoomRatio: '数码变焦倍率',
  ExifImageHeight: 'Exif 图像高度',
  ExifImageWidth: 'Exif 图像宽度',
  ExifVersion: 'Exif 版本',
  ExposureCompensation: '曝光补偿',
  ExposureMode: '曝光模式',
  ExposureProgram: '曝光程序',
  ExposureTime: '曝光时间',
  Flash: '闪光灯',
  FNumber: '光圈 (F)',
  FocalLength: '焦距',
  FocalLengthIn35mmFormat: '等效焦距 (35mm)',
  GPSAltitudeRef: 'GPS 海拔基准',
  GPSDateStamp: 'GPS 日期',
  GPSDestBearing: 'GPS 目标方位',
  GPSDestBearingRef: 'GPS 目标方位基准',
  GPSHPositioningError: 'GPS 水平定位误差',
  GPSImgDirection: 'GPS 图像方向',
  GPSImgDirectionRef: 'GPS 图像方向基准',
  GPSLatitudeRef: 'GPS 纬度基准',
  GPSLongitudeRef: 'GPS 经度基准',
  GPSSpeed: 'GPS 速度',
  GPSSpeedRef: 'GPS 速度单位',
  GPSTimeStamp: 'GPS 时间',
  HostComputer: '主机设备',
  ISO: 'ISO 感光度',
  LensInfo: '镜头信息',
  LensMake: '镜头制造商',
  LensModel: '镜头型号',
  Make: '制造商',
  MeteringMode: '测光模式',
  Model: '型号',
  ModifyDate: '修改时间',
  OffsetTime: '时区偏移',
  OffsetTimeDigitized: '数字化时区偏移',
  OffsetTimeOriginal: '原始时区偏移',
  Orientation: '方向',
  ResolutionUnit: '分辨率单位',
  SceneType: '场景类型',
  SensingMethod: '感光方式',
  ShutterSpeedValue: '快门速度值',
  Software: '软件',
  SubjectArea: '主体区域',
  SubSecTimeDigitized: '数字化亚秒时间',
  SubSecTimeOriginal: '原始亚秒时间',
  WhiteBalance: '白平衡',
  XResolution: '水平分辨率',
  YResolution: '垂直分辨率',
  // Common content / rights tags (surfaced in the summary; not in the reference HEIC)
  ImageDescription: '图像描述',
  UserComment: '用户注释',
  Artist: '作者',
  Copyright: '版权',
  ImageUniqueID: '图像 ID',
  Rating: '评分',
  Subject: '主题',
  Padding: '填充',

  // Composite (derived)
  Aperture: '光圈',
  CircleOfConfusion: '弥散圆',
  FocalLength35efl: '等效焦距 (35mm)',
  FOV: '视角',
  GPSAltitude: 'GPS 海拔',
  GPSDateTime: 'GPS 日期时间',
  GPSLatitude: 'GPS 纬度',
  GPSLongitude: 'GPS 经度',
  GPSPosition: 'GPS 坐标',
  HyperfocalDistance: '超焦距',
  ImageSize: '图像尺寸',
  LensID: '镜头标识',
  LightValue: '光值 (EV)',
  Megapixels: '百万像素',
  RunTimeSincePowerUp: '开机运行时间',
  ScaleFactor35efl: '35mm 换算系数',
  ShutterSpeed: '快门速度',
  SubSecCreateDate: '创建时间 (亚秒)',
  SubSecDateTimeOriginal: '原始拍摄时间 (亚秒)',
  SubSecModifyDate: '修改时间 (亚秒)',

  // ICC_Profile
  AToB0: 'A2B0 转换表',
  BlueMatrixColumn: '蓝色矩阵列',
  BlueTRC: '蓝色色调响应曲线',
  BToA0: 'B2A0 转换表',
  ChromaticAdaptation: '色彩适应',
  CMMFlags: 'CMM 标志',
  ColorPrimaries: '原色',
  ColorSpaceData: '色彩空间数据',
  ConnectionSpaceIlluminant: '连接空间光源',
  DeviceAttributes: '设备属性',
  DeviceManufacturer: '设备制造商',
  DeviceModel: '设备型号',
  GreenMatrixColumn: '绿色矩阵列',
  GreenTRC: '绿色色调响应曲线',
  HDGainMapInfo: 'HD 增益图信息',
  MatrixCoefficients: '矩阵系数',
  MediaWhitePoint: '媒体白点',
  PrimaryPlatform: '主平台',
  ProfileClass: '配置文件类别',
  ProfileCMMType: '配置文件 CMM 类型',
  ProfileConnectionSpace: '配置文件连接空间',
  ProfileCopyright: '配置文件版权',
  ProfileCreator: '配置文件创建者',
  ProfileDateTime: '配置文件日期',
  ProfileDescription: '配置文件描述',
  ProfileFileSignature: '配置文件签名',
  ProfileID: '配置文件 ID',
  ProfileVersion: '配置文件版本',
  RedMatrixColumn: '红色矩阵列',
  RedTRC: '红色色调响应曲线',
  RenderingIntent: '渲染意图',
  TransferCharacteristics: '传输特性',
  VideoFullRangeFlag: '视频全范围标志',

  // MakerNotes (Apple)
  AccelerationVector: '加速度向量',
  AEAverage: '自动曝光平均值',
  AEStable: '自动曝光稳定',
  AETarget: '自动曝光目标',
  AFConfidence: '对焦置信度',
  AFMeasuredDepth: '对焦测得深度',
  AFPerformance: '对焦性能',
  AFStable: '对焦稳定',
  CameraType: '相机类型',
  ColorTemperature: '色温',
  ContentIdentifier: '内容标识符',
  FocusDistanceRange: '对焦距离范围',
  FocusPosition: '对焦位置',
  HDRGain: 'HDR 增益',
  HDRHeadroom: 'HDR 余量',
  ImageCaptureType: '图像拍摄类型',
  LivePhotoVideoIndex: '实况照片视频索引',
  MakerNoteVersion: '制造商注释版本',
  PhotoIdentifier: '照片标识符',
  PhotosAppFeatureFlags: '照片 App 功能标志',
  RunTimeEpoch: '运行时起点',
  RunTimeFlags: '运行时标志',
  RunTimeScale: '运行时刻度',
  RunTimeValue: '运行时值',
  SemanticStyle: '语义风格',
  SignalToNoiseRatio: '信噪比',

  // QuickTime (HEIF container / HEVC config)
  AuxiliaryImageType: '辅助图像类型',
  AverageFrameRate: '平均帧率',
  BitDepthChroma: '色度位深',
  BitDepthLuma: '亮度位深',
  ChromaFormat: '色度格式',
  ColorProfiles: '色彩配置',
  CompatibleBrands: '兼容品牌',
  ConstantFrameRate: '恒定帧率',
  ConstraintIndicatorFlags: '约束指示标志',
  GeneralLevelIDC: '通用级别 IDC',
  GeneralProfileIDC: '通用配置 IDC',
  GeneralProfileSpace: '通用配置空间',
  GeneralTierFlag: '通用层级标志',
  GenProfileCompatibilityFlags: '通用配置兼容标志',
  HandlerType: '处理器类型',
  HEVCConfigurationVersion: 'HEVC 配置版本',
  ImagePixelDepth: '图像像素深度',
  ImageSpatialExtent: '图像空间范围',
  MajorBrand: '主品牌',
  MediaDataOffset: '媒体数据偏移',
  MediaDataSize: '媒体数据大小',
  MetaImageSize: '元图像尺寸',
  MinorVersion: '次版本',
  MinSpatialSegmentationIDC: '最小空间分割 IDC',
  NumTemporalLayers: '时间层数',
  ParallelismType: '并行类型',
  PrimaryItemReference: '主项目引用',
  Rotation: '旋转',
  TemporalIDNested: '时间 ID 嵌套',

  // XMP
  HDRGainMapHeadroom: 'HDR 增益图余量',
  HDRGainMapVersion: 'HDR 增益图版本',
  XMPToolkit: 'XMP 工具包',
  About: '关于',

  // ExifTool envelope
  ExifToolVersion: 'ExifTool 版本',
  Warning: '警告',
}

/** Localised label for an Exif tag field name. English uses the raw ExifTool name; zh-CN uses the
 *  map above, falling back to the raw name for any tag without a translation. */
export function tagLabel(key: string, lang: AppLanguage): string {
  return lang === 'zh-CN' ? (ZH[key] ?? key) : key
}
